version: 3

env:
  GOEXPERIMENT: runtimesecret

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    vars:
      API_DIRS: '{{.ROOT_DIR}}/api/operations/v1alpha1/... {{.ROOT_DIR}}/api/shared/...'
      MANIFEST_OUT: '{{.ROOT_DIR}}/charts/platform-mesh-controller/crds'
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/operations/v1alpha1/... {{.ROOT_DIR}}/api/shared/...'
      COMPONENTS: 'platform-mesh-controller '
      REPO_URL: 'https://github.com/opekcm/platform-mesh-controller'
      CHART_COMPONENTS: "platform-mesh-controller"
      CRDS_COMPONENTS: 'platform-mesh-controller '
      CRDS_PATH: '{{.ROOT_DIR}}/charts/platform-mesh-controller/crds'
      SKIP_VALIDATION_TESTS: 'true'
