apiVersion: v2
name: pm-integration
description: >-
  Platform Mesh portal metadata
  (APIExport/APIResourceSchema/ProviderMetadata/ContentConfiguration) to be
  applied in the KCP control plane.
type: application
version: 0.10.9
appVersion: 0.10.9
kubeVersion: ">=1.22.0-0"
keywords:
  - openkcm
  - kcp
  - platform-mesh
sources:
  - https://github.com/openkcm/platform-mesh-controller
maintainers:
  - name: OpenKCM
    url: https://openkcm.io
