global:
  commonLabels: {}

nameOverride: ""
fullnameOverride: ""

rbac:
  enabled: false

publicScheme: "http"
publicHost: "localhost"

metadata:
  contentPath: "/pm-content.json"
  namespaceContentPath: "/pm-content-namespace.json"

branding:
  marketplace:
    title: "OpenKCM"
    description: "Kubernetes cluster lifecycle and sovereign key management powered by OpenKCM."
