apiVersion: v1
kind: ServiceAccount
metadata:
  name: openkcm-controller-manager
  labels:
    {{- include "operator.labels" . | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ .name }}
{{- end }}
{{- end }}
