apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "platform-mesh-controller.fullname" .) }}
  namespace: {{ include "platform-mesh-controller.namespace" . }}
  labels:
    {{- include "platform-mesh-controller.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
    - name: health
      port: 8081
      protocol: TCP
      targetPort: health
  selector:
    {{- include "platform-mesh-controller.selectorLabels" . | nindent 4 }}
