apiVersion: v1
kind: Service
metadata:
  name: platform-mesh-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
    - name: health
      port: 8081
      protocol: TCP
      targetPort: health
  selector:
    control-plane: controller-manager
