//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/openkcm/openkcm-controller/api/shared"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSRolesAnywhereConfig) DeepCopyInto(out *AWSRolesAnywhereConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSRolesAnywhereConfig.
func (in *AWSRolesAnywhereConfig) DeepCopy() *AWSRolesAnywhereConfig {
	if in == nil {
		return nil
	}
	out := new(AWSRolesAnywhereConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSRootKey) DeepCopyInto(out *AWSRootKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSRootKey.
func (in *AWSRootKey) DeepCopy() *AWSRootKey {
	if in == nil {
		return nil
	}
	out := new(AWSRootKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSRootKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSRootKeyList) DeepCopyInto(out *AWSRootKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSRootKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSRootKeyList.
func (in *AWSRootKeyList) DeepCopy() *AWSRootKeyList {
	if in == nil {
		return nil
	}
	out := new(AWSRootKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSRootKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSRootKeySpec) DeepCopyInto(out *AWSRootKeySpec) {
	*out = *in
	out.RolesAnywhere = in.RolesAnywhere
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSRootKeySpec.
func (in *AWSRootKeySpec) DeepCopy() *AWSRootKeySpec {
	if in == nil {
		return nil
	}
	out := new(AWSRootKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSRootKeyStatus) DeepCopyInto(out *AWSRootKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CryptoState != nil {
		in, out := &in.CryptoState, &out.CryptoState
		*out = new(shared.CryptoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSRootKeyStatus.
func (in *AWSRootKeyStatus) DeepCopy() *AWSRootKeyStatus {
	if in == nil {
		return nil
	}
	out := new(AWSRootKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureFederatedIdentityConfig) DeepCopyInto(out *AzureFederatedIdentityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureFederatedIdentityConfig.
func (in *AzureFederatedIdentityConfig) DeepCopy() *AzureFederatedIdentityConfig {
	if in == nil {
		return nil
	}
	out := new(AzureFederatedIdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureRootKey) DeepCopyInto(out *AzureRootKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureRootKey.
func (in *AzureRootKey) DeepCopy() *AzureRootKey {
	if in == nil {
		return nil
	}
	out := new(AzureRootKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureRootKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureRootKeyList) DeepCopyInto(out *AzureRootKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureRootKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureRootKeyList.
func (in *AzureRootKeyList) DeepCopy() *AzureRootKeyList {
	if in == nil {
		return nil
	}
	out := new(AzureRootKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureRootKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureRootKeySpec) DeepCopyInto(out *AzureRootKeySpec) {
	*out = *in
	out.FederatedIdentity = in.FederatedIdentity
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureRootKeySpec.
func (in *AzureRootKeySpec) DeepCopy() *AzureRootKeySpec {
	if in == nil {
		return nil
	}
	out := new(AzureRootKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureRootKeyStatus) DeepCopyInto(out *AzureRootKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CryptoState != nil {
		in, out := &in.CryptoState, &out.CryptoState
		*out = new(shared.CryptoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureRootKeyStatus.
func (in *AzureRootKeyStatus) DeepCopy() *AzureRootKeyStatus {
	if in == nil {
		return nil
	}
	out := new(AzureRootKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataEncryptionKey) DeepCopyInto(out *DataEncryptionKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataEncryptionKey.
func (in *DataEncryptionKey) DeepCopy() *DataEncryptionKey {
	if in == nil {
		return nil
	}
	out := new(DataEncryptionKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataEncryptionKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataEncryptionKeyKMIP) DeepCopyInto(out *DataEncryptionKeyKMIP) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataEncryptionKeyKMIP.
func (in *DataEncryptionKeyKMIP) DeepCopy() *DataEncryptionKeyKMIP {
	if in == nil {
		return nil
	}
	out := new(DataEncryptionKeyKMIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataEncryptionKeyList) DeepCopyInto(out *DataEncryptionKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataEncryptionKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataEncryptionKeyList.
func (in *DataEncryptionKeyList) DeepCopy() *DataEncryptionKeyList {
	if in == nil {
		return nil
	}
	out := new(DataEncryptionKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataEncryptionKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataEncryptionKeySpec) DeepCopyInto(out *DataEncryptionKeySpec) {
	*out = *in
	if in.KMIP != nil {
		in, out := &in.KMIP, &out.KMIP
		*out = new(DataEncryptionKeyKMIP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataEncryptionKeySpec.
func (in *DataEncryptionKeySpec) DeepCopy() *DataEncryptionKeySpec {
	if in == nil {
		return nil
	}
	out := new(DataEncryptionKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataEncryptionKeyStatus) DeepCopyInto(out *DataEncryptionKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CryptoState != nil {
		in, out := &in.CryptoState, &out.CryptoState
		*out = new(shared.CryptoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataEncryptionKeyStatus.
func (in *DataEncryptionKeyStatus) DeepCopy() *DataEncryptionKeyStatus {
	if in == nil {
		return nil
	}
	out := new(DataEncryptionKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainKey) DeepCopyInto(out *DomainKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainKey.
func (in *DomainKey) DeepCopy() *DomainKey {
	if in == nil {
		return nil
	}
	out := new(DomainKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainKeyList) DeepCopyInto(out *DomainKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DomainKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainKeyList.
func (in *DomainKeyList) DeepCopy() *DomainKeyList {
	if in == nil {
		return nil
	}
	out := new(DomainKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainKeySpec) DeepCopyInto(out *DomainKeySpec) {
	*out = *in
	if in.PrimaryRootKeyRef != nil {
		in, out := &in.PrimaryRootKeyRef, &out.PrimaryRootKeyRef
		*out = new(shared.TypedReference)
		**out = **in
	}
	if in.FallbackRootKeyRefs != nil {
		in, out := &in.FallbackRootKeyRefs, &out.FallbackRootKeyRefs
		*out = make([]shared.TypedReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainKeySpec.
func (in *DomainKeySpec) DeepCopy() *DomainKeySpec {
	if in == nil {
		return nil
	}
	out := new(DomainKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainKeyStatus) DeepCopyInto(out *DomainKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CryptoState != nil {
		in, out := &in.CryptoState, &out.CryptoState
		*out = new(shared.CryptoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainKeyStatus.
func (in *DomainKeyStatus) DeepCopy() *DomainKeyStatus {
	if in == nil {
		return nil
	}
	out := new(DomainKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPRootKey) DeepCopyInto(out *GCPRootKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPRootKey.
func (in *GCPRootKey) DeepCopy() *GCPRootKey {
	if in == nil {
		return nil
	}
	out := new(GCPRootKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPRootKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPRootKeyList) DeepCopyInto(out *GCPRootKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPRootKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPRootKeyList.
func (in *GCPRootKeyList) DeepCopy() *GCPRootKeyList {
	if in == nil {
		return nil
	}
	out := new(GCPRootKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPRootKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPRootKeySpec) DeepCopyInto(out *GCPRootKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPRootKeySpec.
func (in *GCPRootKeySpec) DeepCopy() *GCPRootKeySpec {
	if in == nil {
		return nil
	}
	out := new(GCPRootKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPRootKeyStatus) DeepCopyInto(out *GCPRootKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CryptoState != nil {
		in, out := &in.CryptoState, &out.CryptoState
		*out = new(shared.CryptoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPRootKeyStatus.
func (in *GCPRootKeyStatus) DeepCopy() *GCPRootKeyStatus {
	if in == nil {
		return nil
	}
	out := new(GCPRootKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HSMRootKey) DeepCopyInto(out *HSMRootKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HSMRootKey.
func (in *HSMRootKey) DeepCopy() *HSMRootKey {
	if in == nil {
		return nil
	}
	out := new(HSMRootKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HSMRootKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HSMRootKeyList) DeepCopyInto(out *HSMRootKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HSMRootKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HSMRootKeyList.
func (in *HSMRootKeyList) DeepCopy() *HSMRootKeyList {
	if in == nil {
		return nil
	}
	out := new(HSMRootKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HSMRootKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HSMRootKeySpec) DeepCopyInto(out *HSMRootKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HSMRootKeySpec.
func (in *HSMRootKeySpec) DeepCopy() *HSMRootKeySpec {
	if in == nil {
		return nil
	}
	out := new(HSMRootKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HSMRootKeyStatus) DeepCopyInto(out *HSMRootKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CryptoState != nil {
		in, out := &in.CryptoState, &out.CryptoState
		*out = new(shared.CryptoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HSMRootKeyStatus.
func (in *HSMRootKeyStatus) DeepCopy() *HSMRootKeyStatus {
	if in == nil {
		return nil
	}
	out := new(HSMRootKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCProvider) DeepCopyInto(out *OIDCProvider) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCProvider.
func (in *OIDCProvider) DeepCopy() *OIDCProvider {
	if in == nil {
		return nil
	}
	out := new(OIDCProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoCertAuthConfig) DeepCopyInto(out *OpenBaoCertAuthConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoCertAuthConfig.
func (in *OpenBaoCertAuthConfig) DeepCopy() *OpenBaoCertAuthConfig {
	if in == nil {
		return nil
	}
	out := new(OpenBaoCertAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoRootKey) DeepCopyInto(out *OpenBaoRootKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoRootKey.
func (in *OpenBaoRootKey) DeepCopy() *OpenBaoRootKey {
	if in == nil {
		return nil
	}
	out := new(OpenBaoRootKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoRootKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoRootKeyList) DeepCopyInto(out *OpenBaoRootKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenBaoRootKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoRootKeyList.
func (in *OpenBaoRootKeyList) DeepCopy() *OpenBaoRootKeyList {
	if in == nil {
		return nil
	}
	out := new(OpenBaoRootKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoRootKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoRootKeySpec) DeepCopyInto(out *OpenBaoRootKeySpec) {
	*out = *in
	out.CertAuth = in.CertAuth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoRootKeySpec.
func (in *OpenBaoRootKeySpec) DeepCopy() *OpenBaoRootKeySpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoRootKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoRootKeyStatus) DeepCopyInto(out *OpenBaoRootKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CryptoState != nil {
		in, out := &in.CryptoState, &out.CryptoState
		*out = new(shared.CryptoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoRootKeyStatus.
func (in *OpenBaoRootKeyStatus) DeepCopy() *OpenBaoRootKeyStatus {
	if in == nil {
		return nil
	}
	out := new(OpenBaoRootKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKey) DeepCopyInto(out *ServiceKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKey.
func (in *ServiceKey) DeepCopy() *ServiceKey {
	if in == nil {
		return nil
	}
	out := new(ServiceKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKeyList) DeepCopyInto(out *ServiceKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKeyList.
func (in *ServiceKeyList) DeepCopy() *ServiceKeyList {
	if in == nil {
		return nil
	}
	out := new(ServiceKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKeySpec) DeepCopyInto(out *ServiceKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKeySpec.
func (in *ServiceKeySpec) DeepCopy() *ServiceKeySpec {
	if in == nil {
		return nil
	}
	out := new(ServiceKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKeyStatus) DeepCopyInto(out *ServiceKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CryptoState != nil {
		in, out := &in.CryptoState, &out.CryptoState
		*out = new(shared.CryptoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKeyStatus.
func (in *ServiceKeyStatus) DeepCopy() *ServiceKeyStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tenant) DeepCopyInto(out *Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tenant.
func (in *Tenant) DeepCopy() *Tenant {
	if in == nil {
		return nil
	}
	out := new(Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantList) DeepCopyInto(out *TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantList.
func (in *TenantList) DeepCopy() *TenantList {
	if in == nil {
		return nil
	}
	out := new(TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSpec) DeepCopyInto(out *TenantSpec) {
	*out = *in
	if in.OIDCProvider != nil {
		in, out := &in.OIDCProvider, &out.OIDCProvider
		*out = new(OIDCProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSpec.
func (in *TenantSpec) DeepCopy() *TenantSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStatus) DeepCopyInto(out *TenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStatus.
func (in *TenantStatus) DeepCopy() *TenantStatus {
	if in == nil {
		return nil
	}
	out := new(TenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRootKey) DeepCopyInto(out *VaultRootKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRootKey.
func (in *VaultRootKey) DeepCopy() *VaultRootKey {
	if in == nil {
		return nil
	}
	out := new(VaultRootKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultRootKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRootKeyList) DeepCopyInto(out *VaultRootKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultRootKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRootKeyList.
func (in *VaultRootKeyList) DeepCopy() *VaultRootKeyList {
	if in == nil {
		return nil
	}
	out := new(VaultRootKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultRootKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRootKeySpec) DeepCopyInto(out *VaultRootKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRootKeySpec.
func (in *VaultRootKeySpec) DeepCopy() *VaultRootKeySpec {
	if in == nil {
		return nil
	}
	out := new(VaultRootKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultRootKeyStatus) DeepCopyInto(out *VaultRootKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReconciliationStatus != nil {
		in, out := &in.ReconciliationStatus, &out.ReconciliationStatus
		*out = new(shared.ReconciliationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CryptoState != nil {
		in, out := &in.CryptoState, &out.CryptoState
		*out = new(shared.CryptoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultRootKeyStatus.
func (in *VaultRootKeyStatus) DeepCopy() *VaultRootKeyStatus {
	if in == nil {
		return nil
	}
	out := new(VaultRootKeyStatus)
	in.DeepCopyInto(out)
	return out
}
