apiVersion: v2
name: platform-mesh-controller
description: Helm chart for OpenKCM integration to Platform Mesh
type: application
version: 0.10.9
appVersion: "0.10.9"
kubeVersion: ">=1.22.0-0"
keywords:
  - openkcm
sources:
  - https://github.com/openkcm/platform-mesh-controller
maintainers:
  - name: OpenKCM
    url: https://openkcm.io
